# Generated by pipeline-platform 1.2.0 from access.yml. Do not edit.
# team payments

path "ci/data/payments/*" {
  capabilities = ["read"]
}

path "ci/metadata/payments/*" {
  capabilities = ["list"]
}

path "database/creds/payments-ro" {
  capabilities = ["read"]
}
