# Generated by pipeline-platform 1.2.0 from access.yml. Do not edit.
# team platform

path "ci/data/*" {
  capabilities = ["read"]
}

path "ci/data/platform/*" {
  capabilities = ["create", "read", "update", "delete"]
}

path "ci/metadata/*" {
  capabilities = ["list"]
}
