#!/bin/sh
# Generated by pipeline-platform 1.2.0 from access.yml. Do not edit.
# Needs VAULT_ADDR and a token allowed to manage policies. Safe to run repeatedly.
set -eu
cd "$(dirname "$0")"

vault policy write team-orders policies/team-orders.hcl
vault policy write team-payments policies/team-payments.hcl
vault policy write team-platform policies/team-platform.hcl
vault policy write user-dave policies/user-dave.hcl
# orders: attach the policy to each member in your auth method, e.g. vault write auth/<method>/users/alice policies=team-orders; vault write auth/<method>/users/bob policies=team-orders
vault write identity/group name=team-payments type=external policies=team-payments
# once per IdP group: vault write identity/group-alias name=payments mount_accessor=<oidc accessor> canonical_id=<id of group team-payments>
vault write identity/group name=team-platform type=external policies=team-platform
# once per IdP group: vault write identity/group-alias name=platform-sre mount_accessor=<oidc accessor> canonical_id=<id of group team-platform>
vault write auth/jwt/role/ci-shop-orders-api @roles/ci-shop-orders-api.json
vault write auth/jwt/role/ci-shop-payments-api @roles/ci-shop-payments-api.json
