"""Team-based access: one access.yml -> Vault policies and Kubernetes RBAC.

Teams own sections of a service (a Vault path prefix, a Kubernetes namespace). Grants name the
section and the rights explicitly; the files rendered here are plain Vault HCL and Kubernetes YAML
that can be reviewed in a merge request and applied by a pipeline.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

import yaml

from . import __version__
from .schema import Issue, validate_schema

SCHEMA = "access.v1.schema.json"
CAPS = ["create", "read", "update", "patch", "delete", "list"]  # canonical order in the output
FORBIDDEN_ROOTS = ("sys", "auth", "identity")  # policy/auth administration is not delegated here
HEADER = f"# Generated by pipeline-platform {__version__} from access.yml. Do not edit.\n"


def validate(doc: Any) -> list[Issue]:
    issues = validate_schema(doc, SCHEMA)
    if issues:
        return issues
    teams = doc["teams"]
    for i, g in enumerate(doc.get("grants", [])):
        if "team" in g and g["team"] not in teams:
            issues.append(Issue(f"grants[{i}].team", f"unknown team '{g['team']}'"))
        for j, v in enumerate(g.get("vault", [])):
            issues += _vault_path_issues(f"grants[{i}].vault[{j}]", v)
        for j, k in enumerate(g.get("k8s", [])):
            if k["role"] == "cluster-admin":
                issues.append(
                    Issue(f"grants[{i}].k8s[{j}].role", "cluster-admin is not granted through this file")
                )
    for i, c in enumerate(doc.get("ci", [])):
        if c["team"] not in teams:
            issues.append(Issue(f"ci[{i}].team", f"unknown team '{c['team']}'"))
    seen: set[str] = set()
    for i, c in enumerate(doc.get("ci", [])):
        if c["project"] in seen:
            issues.append(Issue(f"ci[{i}].project", f"duplicate project '{c['project']}'"))
        seen.add(c["project"])
    return sorted(issues, key=lambda x: (x.path, x.message))


def _vault_path_issues(where: str, v: dict[str, Any]) -> list[Issue]:
    path = v["path"].strip("/")
    first = path.split("/", 1)[0]
    if first in FORBIDDEN_ROOTS or first in ("*", "+") or path.startswith("*"):
        return [
            Issue(
                f"{where}.path", f"'{v['path']}' is an administrative or root-wide path; not delegated here"
            )
        ]
    if v.get("engine", "kv2") == "kv2" and "/" not in path:
        return [Issue(f"{where}.path", "kv2 paths need mount/path (e.g. ci/payments/*)")]
    return []


# ----------------------------------------------------------------------------- model


@dataclass
class Principal:
    kind: str  # "team" | "user"
    name: str
    vault: dict[tuple[str, str], set[str]] = field(default_factory=dict)  # (engine, path) -> capabilities
    k8s: set[tuple[str, str]] = field(default_factory=set)  # (namespace, role)

    @property
    def policy(self) -> str:
        return f"{self.kind}-{self.name}"


def principals(doc: dict[str, Any]) -> list[Principal]:
    found: dict[tuple[str, str], Principal] = {}
    for g in doc.get("grants", []):
        key = ("team", g["team"]) if "team" in g else ("user", g["user"])
        p = found.setdefault(key, Principal(*key))
        for v in g.get("vault", []):
            p.vault.setdefault((v.get("engine", "kv2"), v["path"].strip("/")), set()).update(v["can"])
        p.k8s.update((k["namespace"], k["role"]) for k in g.get("k8s", []))
    return [found[k] for k in sorted(found)]


def _caps(caps: set[str]) -> str:
    return json.dumps([c for c in CAPS if c in caps])


def policy_hcl(p: Principal) -> str:
    out = [HEADER + f"# {p.kind} {p.name}\n"]
    rules: dict[str, set[str]] = {}
    for (engine, path), caps in sorted(p.vault.items()):
        if engine == "kv2":
            mount, rest = path.split("/", 1)
            rules.setdefault(f"{mount}/data/{rest}", set()).update(caps - {"list"})
            if "list" in caps:
                rules.setdefault(f"{mount}/metadata/{rest}", set()).add("list")
        else:
            rules.setdefault(path, set()).update(caps)
    # Vault applies only the most specific matching rule, so a narrow rule must repeat the rights
    # of the wider globs above it (otherwise `ci/*` read + `ci/platform/*` write would lose the read).
    for path in sorted(rules, key=len):
        for wide, caps in list(rules.items()):
            if wide != path and wide.endswith("*") and path.startswith(wide[:-1]):
                rules[path] = rules[path] | caps
    for path in sorted(rules):
        if rules[path]:
            out.append(f'path "{path}" {{\n  capabilities = {_caps(rules[path])}\n}}\n')
    return "\n".join(out)


def ci_role(c: dict[str, Any], policy: str) -> dict[str, Any]:
    return {
        "role_type": "jwt",
        "user_claim": "project_path",
        "policies": [policy],
        "bound_audiences": [c["audience"]],
        "token_explicit_max_ttl": 900,
        "bound_claims_type": "glob",
        "bound_claims": {"project_path": c["project"], "ref_protected": "true"},
    }


def ci_role_name(project: str) -> str:
    return "ci-" + project.replace("/", "-").replace(".", "-")


def _subjects(doc: dict[str, Any], p: Principal) -> list[dict[str, str]]:
    api = "rbac.authorization.k8s.io"
    if p.kind == "user":
        return [{"kind": "User", "name": p.name, "apiGroup": api}]
    team = doc["teams"][p.name]
    if "group" in team:
        return [{"kind": "Group", "name": team["group"], "apiGroup": api}]
    return [{"kind": "User", "name": m, "apiGroup": api} for m in sorted(team["members"])]


def rbac_yaml(doc: dict[str, Any], plist: list[Principal]) -> str:
    docs = []
    for p in plist:
        for ns, role in sorted(p.k8s):
            docs.append(
                {
                    "apiVersion": "rbac.authorization.k8s.io/v1",
                    "kind": "RoleBinding",
                    "metadata": {
                        "name": f"pp-{p.kind}-{p.name}-{role}".replace(":", "-").replace(".", "-"),
                        "namespace": ns,
                        "labels": {"app.kubernetes.io/managed-by": "pipeline-platform"},
                    },
                    "roleRef": {"apiGroup": "rbac.authorization.k8s.io", "kind": "ClusterRole", "name": role},
                    "subjects": _subjects(doc, p),
                }
            )
    docs.sort(key=lambda d: (d["metadata"]["namespace"], d["metadata"]["name"]))
    return HEADER + "---\n".join(yaml.safe_dump(d, sort_keys=False) for d in docs)


def apply_script(doc: dict[str, Any], plist: list[Principal]) -> str:
    lines = [
        "#!/bin/sh",
        HEADER.rstrip(),
        "# Needs VAULT_ADDR and a token allowed to manage policies. Safe to run repeatedly.",
        "set -eu",
        'cd "$(dirname "$0")"',
        "",
    ]
    for p in plist:
        if p.vault:
            lines.append(f"vault policy write {p.policy} policies/{p.policy}.hcl")
    for name in sorted(doc["teams"]):
        t = doc["teams"][name]
        if f"team-{name}" not in {p.policy for p in plist if p.vault}:
            continue
        if "group" in t:
            lines += [
                f"vault write identity/group name=team-{name} type=external policies=team-{name}",
                f"# once per IdP group: vault write identity/group-alias name={t['group']} "
                f"mount_accessor=<oidc accessor> canonical_id=<id of group team-{name}>",
            ]
        else:
            lines.append(
                f"# {name}: attach the policy to each member in your auth method, e.g. "
                + "; ".join(
                    f"vault write auth/<method>/users/{m} policies=team-{name}" for m in sorted(t["members"])
                )
            )
    for c in sorted(doc.get("ci", []), key=lambda c: c["project"]):
        mount = c.get("auth_path", "jwt")
        role = ci_role_name(c["project"])
        lines.append(f"vault write auth/{mount}/role/{role} @roles/{role}.json")
    return "\n".join(lines) + "\n"


def render(doc: dict[str, Any]) -> dict[str, str]:
    """Relative path -> file content. Input must be valid."""
    plist = principals(doc)
    files: dict[str, str] = {}
    for p in plist:
        if p.vault:
            files[f"vault/policies/{p.policy}.hcl"] = policy_hcl(p)
    for c in doc.get("ci", []):
        files[f"vault/roles/{ci_role_name(c['project'])}.json"] = (
            json.dumps(ci_role(c, f"team-{c['team']}"), indent=2) + "\n"
        )
    files["vault/apply.sh"] = apply_script(doc, plist)
    if any(p.k8s for p in plist):
        files["k8s/rbac.yaml"] = rbac_yaml(doc, plist)
    return files


def who(doc: dict[str, Any], name: str) -> list[str]:
    """Human-readable effective rights of a team or a user (user = own grants + their teams)."""
    wanted = [("team", name)] if name in doc["teams"] else [("user", name)]
    wanted += [("team", t) for t, v in sorted(doc["teams"].items()) if name in v.get("members", [])]
    lines = []
    for p in principals(doc):
        if (p.kind, p.name) not in wanted:
            continue
        for (engine, path), caps in sorted(p.vault.items()):
            lines.append(
                f"{p.kind} {p.name}: vault {path} [{engine}] {','.join(c for c in CAPS if c in caps)}"
            )
        lines += [f"{p.kind} {p.name}: k8s {ns} {role}" for ns, role in sorted(p.k8s)]
    return lines
